included:
  - Sources
  - Tests

excluded:
  - .build

opt_in_rules:
  - empty_count
  - closure_spacing
  - fatal_error_message
  - first_where
  - toggle_bool

disabled_rules:
  - trailing_comma
  - identifier_name

line_length:
  warning: 120
  error: 150

type_body_length:
  warning: 300
  error: 500

file_length:
  warning: 500
  error: 1000
